export type Track =
  | "signal-quality"
  | "responsiveness"
  | "plasticity"
  | "closed-loop-learning"
  | "retention"
  | "reproducibility";

export type Grade = "A" | "B" | "C" | "D" | "Unscored";

export type TrackDef = {
  id: Track;
  name: string;
  short: string;
  description: string;
  measures: string[];
  excludes: string[];
  metrics: { name: string; description: string; unit?: string }[];
  requiredInputs: string[];
  requiredControls: string[];
  scoringFormula: string;
  failureModes: string[];
};

export const TRACKS: TrackDef[] = [
  {
    id: "signal-quality",
    name: "Signal Quality",
    short: "Is the recording stable, active, usable",
    description:
      "Whether the organoid recording is stable, active, and usable as a substrate for downstream benchmarking.",
    measures: [
      "Active channel count",
      "Mean firing rate",
      "Burst rate",
      "Signal-to-noise ratio",
      "Recording stability",
      "Artifact rate",
    ],
    excludes: ["Task performance", "Learning", "Plasticity claims"],
    metrics: [
      { name: "Active channels", description: "Channels with stable spiking above threshold", unit: "#" },
      { name: "Mean firing rate", description: "Spikes per active channel per second", unit: "Hz" },
      { name: "Burst rate", description: "Network bursts per minute", unit: "bpm" },
      { name: "SNR", description: "Peak spike amplitude over RMS baseline", unit: "ratio" },
      { name: "Stability", description: "Drift-adjusted firing rate stability", unit: "0–1" },
      { name: "Artifact rate", description: "Fraction of rejected samples", unit: "0–1" },
    ],
    requiredInputs: [
      "Raw or filtered traces per channel",
      "Sampling rate",
      "Electrode count and layout",
      "Spike detection method",
    ],
    requiredControls: [
      "Artifact exclusion protocol",
      "Baseline activity window",
      "Sham-electrode reference when available",
    ],
    scoringFormula:
      "Min-max across metrics, penalized by missing metadata. Missing sampling rate produces Unscored.",
    failureModes: [
      "Spike rate reported without artifact rejection",
      "Single short session used to claim stability",
      "Mixing spontaneous and evoked windows",
    ],
  },
  {
    id: "responsiveness",
    name: "Responsiveness",
    short: "Does activity change reliably after stimulation",
    description:
      "Whether neural activity changes reliably and with the expected structure after defined stimulation.",
    measures: [
      "Evoked response reliability",
      "Response latency",
      "Stimulus specificity",
      "Response amplitude",
      "Probability of spike after stimulus",
    ],
    excludes: ["Learning from feedback", "Long-term plasticity", "Retention"],
    metrics: [
      { name: "Evoked reliability", description: "Fraction of stimuli eliciting a response above baseline", unit: "0–1" },
      { name: "Response latency", description: "Median spike latency after stimulus", unit: "ms" },
      { name: "Specificity", description: "Response difference between stimulus types", unit: "d'" },
      { name: "Amplitude", description: "Peak evoked population rate", unit: "Hz" },
    ],
    requiredInputs: [
      "Stimulation log with timestamps",
      "Stimulus parameters",
      "Per-channel responses",
    ],
    requiredControls: [
      "Sham stimulation",
      "Inter-stimulus interval randomization",
      "Null-stimulation baseline",
    ],
    scoringFormula:
      "Weighted combination of reliability, latency consistency, and stimulus specificity.",
    failureModes: [
      "Response reported without a null-stimulation baseline",
      "Response to artifact conflated with neural response",
    ],
  },
  {
    id: "plasticity",
    name: "Plasticity",
    short: "Does the system change lastingly from experience",
    description:
      "Whether the network changes its response structure after a defined induction protocol, and whether that change persists.",
    measures: [
      "Pre-post response change",
      "Induction protocol dependence",
      "Persistence window",
      "Specificity to paired pathways",
    ],
    excludes: ["General task learning", "Behavioral proxies"],
    metrics: [
      { name: "Induced change", description: "Effect size of post-induction response vs baseline", unit: "Cohen's d" },
      { name: "Persistence", description: "Retention of change at 30 min post", unit: "0–1" },
      { name: "Specificity", description: "Change on paired vs unpaired pathways", unit: "ratio" },
    ],
    requiredInputs: [
      "Pre-induction baseline",
      "Induction protocol log",
      "Post-induction sampling at multiple time points",
    ],
    requiredControls: [
      "Unpaired-pathway control",
      "Sham induction",
      "Drug block condition where relevant",
    ],
    scoringFormula: "Effect size of induction, weighted by specificity and persistence.",
    failureModes: [
      "Single post-induction time point used for persistence claim",
      "No unpaired control",
    ],
  },
  {
    id: "closed-loop-learning",
    name: "Closed-Loop Learning",
    short: "Does behavior improve under a task with contingent feedback",
    description:
      "Whether a closed-loop organoid system improves task-relevant behavior across sessions when feedback is contingent.",
    measures: [
      "Task reward over time",
      "Learning slope",
      "Feedback-contingent improvement",
      "Decoder lift above frozen baseline",
      "Generalization",
    ],
    excludes: [
      "Intelligence",
      "Consciousness",
      "General cognition",
      "Human-like learning",
    ],
    metrics: [
      { name: "Learning gain", description: "End-of-session reward minus baseline, normalized", unit: "0–1" },
      { name: "Learning slope", description: "Session-level improvement rate", unit: "d-reward/d-session" },
      { name: "Contingent lift", description: "Improvement above random-feedback control", unit: "ratio" },
      { name: "Decoder lift", description: "Improvement above frozen-decoder baseline", unit: "ratio" },
    ],
    requiredInputs: [
      "Session log with rewards and actions",
      "Decoder or controller description",
      "Task environment definition",
    ],
    requiredControls: [
      "Random feedback",
      "Sham stimulation",
      "Frozen decoder",
      "Decoder-only",
      "Null stimulation",
    ],
    scoringFormula:
      "Learning gain above random-feedback control, capped unless all required controls are present.",
    failureModes: [
      "Claiming learning without a random-feedback control",
      "Decoder credited for behavior change it drives alone",
      "Single run used to claim generalization",
    ],
  },
  {
    id: "retention",
    name: "Retention",
    short: "Does learned behavior persist across time",
    description:
      "Whether a closed-loop improvement or plasticity effect persists across days and rebounds on re-exposure.",
    measures: [
      "Retention at 24h",
      "Retention at 7d",
      "Savings on re-exposure",
    ],
    excludes: ["Within-session learning"],
    metrics: [
      { name: "Retention-24h", description: "Performance at 24h relative to end of training", unit: "0–1" },
      { name: "Retention-7d", description: "Performance at 7 days relative to end of training", unit: "0–1" },
      { name: "Savings", description: "Reduction in trials-to-criterion on re-exposure", unit: "ratio" },
    ],
    requiredInputs: [
      "Matched re-test session",
      "Matched organoid identity (batch_id)",
      "Same task environment",
    ],
    requiredControls: [
      "Naive organoid control",
      "Matched session structure",
    ],
    scoringFormula: "Matched re-test performance normalized by end-of-training and naive baselines.",
    failureModes: ["Re-test in a different task or decoder", "Different organoid batch for re-test"],
  },
  {
    id: "reproducibility",
    name: "Reproducibility",
    short: "Does the result replicate across batches and labs",
    description:
      "Whether the result replicates across independent batches, across sessions with matched protocols, and ideally across independent labs.",
    measures: [
      "Replication across batches",
      "Replication across labs",
      "Data openness",
      "Pre-registration",
    ],
    excludes: ["Peer review as a replication signal"],
    metrics: [
      { name: "Batch replication", description: "Effect preserved across independent batches", unit: "0–1" },
      { name: "Lab replication", description: "Effect preserved at an independent lab", unit: "0–1" },
      { name: "Data openness", description: "Fraction of raw, processed, code artifacts public", unit: "0–1" },
    ],
    requiredInputs: [
      "Independent batches",
      "Public protocol",
      "Public data",
    ],
    requiredControls: [
      "Independent lab replication",
      "Pre-registered analysis",
    ],
    scoringFormula: "Average of batch replication, lab replication, and data openness.",
    failureModes: ["Single-batch result", "Private data with public claim"],
  },
];

export const trackById = (id: Track | string): TrackDef =>
  TRACKS.find((t) => t.id === id)!;

export type Controls = {
  randomFeedback: "pass" | "partial" | "missing" | "fail" | "na";
  shamStim: "pass" | "partial" | "missing" | "fail" | "na";
  frozenDecoder: "pass" | "partial" | "missing" | "fail" | "na";
  decoderOnly: "pass" | "partial" | "missing" | "fail" | "na";
  nullStim: "pass" | "partial" | "missing" | "fail" | "na";
  replication: "pass" | "partial" | "missing" | "fail" | "na";
};

export type System = {
  id: string;
  name: string;
  source: string;
  track: Track;
  task: string;
  platform: string;
  stimMethod: string;
  decoder?: string;
  organoidType: string;
  species: string;
  cellLine: string;
  ageDays: number;
  metrics: {
    signal: number;
    response: number;
    plasticity: number;
    learning: number;
    retention: number;
    repro: number;
    composite: number;
  };
  nOrganoids: number;
  nSessions: number;
  nBatches: number;
  nLabs: number;
  controls: Controls;
  grade: Grade;
  availability: {
    raw: boolean;
    processed: boolean;
    code: boolean;
    peerReviewed: boolean;
    openDataset: boolean;
  };
  lastUpdated: string;
  learningCurve: { x: number; y: number; baseline: number }[];
  datasetId?: string;
  limitations: string[];
  paper: {
    title: string;
    authors: string[];
    year: number;
    venue: string;
    peerReviewed: boolean;
    doi?: string;
  };
  culture: string;
  preprocessing: string;
};

function mkCurve(start: number, end: number, noise = 0.02, baseline = 0.2) {
  const n = 20;
  const out: { x: number; y: number; baseline: number }[] = [];
  for (let i = 0; i < n; i++) {
    const t = i / (n - 1);
    const y = start + (end - start) * (1 - Math.exp(-2.5 * t));
    const jit = (Math.sin(i * 1.37) * 0.5 + Math.cos(i * 0.67) * 0.5) * noise;
    out.push({ x: i, y: Math.max(0, Math.min(1, y + jit)), baseline });
  }
  return out;
}

export const SYSTEMS: System[] = [
  {
    id: "ob-sys-0001",
    name: "DishBrain v2.1 — Pong",
    source: "Kagan Lab",
    track: "closed-loop-learning",
    task: "Pong-style goal reaching",
    platform: "MaxOne HD-MEA",
    stimMethod: "Biphasic multi-site electrical stim",
    decoder: "Rate-coded binary policy",
    organoidType: "Cortical cell culture",
    species: "Human (iPSC) + mouse primary",
    cellLine: "Mixed",
    ageDays: 70,
    metrics: { signal: 0.78, response: 0.82, plasticity: 0.68, learning: 0.74, retention: 0.51, repro: 0.66, composite: 0.70 },
    nOrganoids: 38, nSessions: 176, nBatches: 6, nLabs: 2,
    controls: { randomFeedback: "pass", shamStim: "pass", frozenDecoder: "pass", decoderOnly: "pass", nullStim: "pass", replication: "pass" },
    grade: "A",
    availability: { raw: true, processed: true, code: true, peerReviewed: true, openDataset: true },
    lastUpdated: "2026-04-18",
    learningCurve: mkCurve(0.22, 0.78, 0.03, 0.25),
    datasetId: "ob-ds-0001",
    limitations: [
      "Task is a simplified pong; only one axis of feedback",
      "Learning slope is small relative to within-session variance",
      "Retention measured only at 24h",
    ],
    paper: { title: "In vitro neurons learn and exhibit sentience when embodied in a simulated game-world", authors: ["Kagan, B.J. et al."], year: 2022, venue: "Neuron", peerReviewed: true, doi: "10.1016/j.neuron.2022.09.001" },
    culture: "BrainPhys, 2D MEA, dual-modality cortical seeding",
    preprocessing: "Bandpass 300–6000Hz, Kilosort3, manual curation",
  },
  {
    id: "ob-sys-0002",
    name: "Cortical organoid — stim-response map",
    source: "Muotri Lab",
    track: "responsiveness",
    task: "Stimulus-response tuning",
    platform: "Axion Maestro Pro",
    stimMethod: "Multisite electrical pulses",
    organoidType: "Cortical organoid",
    species: "Human (iPSC)",
    cellLine: "H9",
    ageDays: 180,
    metrics: { signal: 0.84, response: 0.79, plasticity: 0.41, learning: 0, retention: 0, repro: 0.72, composite: 0.65 },
    nOrganoids: 54, nSessions: 108, nBatches: 8, nLabs: 1,
    controls: { randomFeedback: "na", shamStim: "pass", frozenDecoder: "na", decoderOnly: "na", nullStim: "pass", replication: "partial" },
    grade: "B",
    availability: { raw: false, processed: true, code: true, peerReviewed: true, openDataset: false },
    lastUpdated: "2026-02-22",
    learningCurve: mkCurve(0.3, 0.42, 0.02, 0.3),
    datasetId: "ob-ds-0002",
    limitations: ["Raw traces not released", "Single-lab replication"],
    paper: { title: "Complex oscillatory waves emerging from cortical organoids model early human brain network development", authors: ["Trujillo, C.A. et al."], year: 2019, venue: "Cell Stem Cell", peerReviewed: true },
    culture: "Dorsal-forebrain protocol, 180d",
    preprocessing: "Axion default + custom burst detection",
  },
  {
    id: "ob-sys-0003",
    name: "FinalSpark CL-01 — target state",
    source: "FinalSpark",
    track: "closed-loop-learning",
    task: "Target-state maintenance",
    platform: "Custom MEA, 4-well",
    stimMethod: "Dopamine + electrical dual-channel",
    decoder: "LDA on population rate",
    organoidType: "Cortical spheroid",
    species: "Human (iPSC)",
    cellLine: "Proprietary",
    ageDays: 120,
    metrics: { signal: 0.72, response: 0.70, plasticity: 0.55, learning: 0.58, retention: 0.44, repro: 0.48, composite: 0.58 },
    nOrganoids: 28, nSessions: 94, nBatches: 4, nLabs: 1,
    controls: { randomFeedback: "pass", shamStim: "pass", frozenDecoder: "pass", decoderOnly: "partial", nullStim: "pass", replication: "missing" },
    grade: "B",
    availability: { raw: false, processed: true, code: false, peerReviewed: false, openDataset: false },
    lastUpdated: "2026-03-30",
    learningCurve: mkCurve(0.25, 0.60, 0.03, 0.28),
    datasetId: "ob-ds-0003",
    limitations: ["Commercial platform; partial public data", "No independent replication yet"],
    paper: { title: "FinalSpark CL-01 technical report", authors: ["Jordan, F. et al."], year: 2025, venue: "Preprint (bioRxiv)", peerReviewed: false },
    culture: "Proprietary 4-well bioreactor",
    preprocessing: "Proprietary spike sorter, exported as parquet",
  },
  {
    id: "ob-sys-0004",
    name: "Cerebral organoid — plasticity induction",
    source: "Lancaster Lab",
    track: "plasticity",
    task: "Paired-pathway induction",
    platform: "3Brain BioCAM DupleX",
    stimMethod: "Theta-burst electrical induction",
    organoidType: "Whole-brain organoid",
    species: "Human (iPSC)",
    cellLine: "HMGU1",
    ageDays: 240,
    metrics: { signal: 0.76, response: 0.62, plasticity: 0.71, learning: 0, retention: 0.58, repro: 0.60, composite: 0.64 },
    nOrganoids: 22, nSessions: 62, nBatches: 3, nLabs: 1,
    controls: { randomFeedback: "na", shamStim: "pass", frozenDecoder: "na", decoderOnly: "na", nullStim: "pass", replication: "partial" },
    grade: "B",
    availability: { raw: true, processed: true, code: true, peerReviewed: true, openDataset: true },
    lastUpdated: "2026-01-12",
    learningCurve: mkCurve(0.3, 0.7, 0.02, 0.32),
    datasetId: "ob-ds-0004",
    limitations: ["Batch size limited by organoid yield", "Drug block control missing for some conditions"],
    paper: { title: "Long-term potentiation in cerebral organoids", authors: ["Lancaster, M.A. et al."], year: 2024, venue: "Nature Neuroscience", peerReviewed: true },
    culture: "Unguided cerebral organoid protocol, 8 months",
    preprocessing: "Open-source, HDF5 + parquet",
  },
  {
    id: "ob-sys-0005",
    name: "BrainXell assembloid — retention",
    source: "BrainXell",
    track: "retention",
    task: "Matched re-exposure",
    platform: "Axion Maestro CytoView",
    stimMethod: "Electrical, patterned",
    decoder: "Logistic regression",
    organoidType: "Cortico-striatal assembloid",
    species: "Human (iPSC)",
    cellLine: "BXS-01",
    ageDays: 150,
    metrics: { signal: 0.70, response: 0.66, plasticity: 0.52, learning: 0.49, retention: 0.68, repro: 0.44, composite: 0.59 },
    nOrganoids: 18, nSessions: 54, nBatches: 3, nLabs: 1,
    controls: { randomFeedback: "partial", shamStim: "pass", frozenDecoder: "missing", decoderOnly: "missing", nullStim: "pass", replication: "missing" },
    grade: "C",
    availability: { raw: false, processed: true, code: false, peerReviewed: false, openDataset: false },
    lastUpdated: "2025-12-02",
    learningCurve: mkCurve(0.26, 0.5, 0.025, 0.3),
    datasetId: "ob-ds-0005",
    limitations: ["Small N batches", "Commercial pipeline not fully public"],
    paper: { title: "Assembloid retention in closed-loop paradigms", authors: ["Chen, L. et al."], year: 2025, venue: "bioRxiv", peerReviewed: false },
    culture: "Fused cortical + striatal organoids",
    preprocessing: "Axion + custom Python",
  },
  {
    id: "ob-sys-0006",
    name: "Knoblich lab — spontaneous activity panel",
    source: "Knoblich Lab",
    track: "signal-quality",
    task: "Spontaneous activity",
    platform: "MaxWell MaxOne",
    stimMethod: "None",
    organoidType: "Cerebral organoid",
    species: "Human (iPSC)",
    cellLine: "KOLF2.1J",
    ageDays: 200,
    metrics: { signal: 0.88, response: 0, plasticity: 0, learning: 0, retention: 0, repro: 0.74, composite: 0.81 },
    nOrganoids: 42, nSessions: 126, nBatches: 5, nLabs: 2,
    controls: { randomFeedback: "na", shamStim: "na", frozenDecoder: "na", decoderOnly: "na", nullStim: "pass", replication: "pass" },
    grade: "A",
    availability: { raw: true, processed: true, code: true, peerReviewed: true, openDataset: true },
    lastUpdated: "2026-03-10",
    learningCurve: mkCurve(0.7, 0.88, 0.015, 0.5),
    datasetId: "ob-ds-0006",
    limitations: ["Signal-quality-only; no stimulation"],
    paper: { title: "Reference spontaneous activity in human cerebral organoids", authors: ["Knoblich, J.A. et al."], year: 2024, venue: "Cell Reports", peerReviewed: true },
    culture: "Guided cerebral organoid",
    preprocessing: "Public pipeline (GitHub)",
  },
  {
    id: "ob-sys-0007",
    name: "Finkbeiner — closed-loop cart-pole",
    source: "Finkbeiner Lab",
    track: "closed-loop-learning",
    task: "Cart-pole balance",
    platform: "MaxOne HD-MEA",
    stimMethod: "Patterned electrical",
    decoder: "LSTM on rate vectors",
    organoidType: "Cortical organoid",
    species: "Human (iPSC)",
    cellLine: "WTC-11",
    ageDays: 160,
    metrics: { signal: 0.74, response: 0.75, plasticity: 0.60, learning: 0.63, retention: 0.48, repro: 0.52, composite: 0.62 },
    nOrganoids: 26, nSessions: 98, nBatches: 4, nLabs: 1,
    controls: { randomFeedback: "pass", shamStim: "pass", frozenDecoder: "pass", decoderOnly: "pass", nullStim: "pass", replication: "missing" },
    grade: "B",
    availability: { raw: true, processed: true, code: true, peerReviewed: false, openDataset: true },
    lastUpdated: "2026-02-05",
    learningCurve: mkCurve(0.24, 0.63, 0.03, 0.25),
    datasetId: "ob-ds-0007",
    limitations: ["Decoder contribution sizable; lift above decoder-only is modest", "Independent replication pending"],
    paper: { title: "Closed-loop cart-pole with cortical organoids", authors: ["Finkbeiner, S. et al."], year: 2025, venue: "bioRxiv", peerReviewed: false },
    culture: "Dorsal forebrain, 5 months",
    preprocessing: "Kilosort3 + Phy curation",
  },
  {
    id: "ob-sys-0008",
    name: "Independent replication 001",
    source: "Independent Consortium",
    track: "reproducibility",
    task: "Re-scoring of ob-sys-0001",
    platform: "MaxOne HD-MEA",
    stimMethod: "Matched to ob-sys-0001",
    decoder: "Matched to ob-sys-0001",
    organoidType: "Cortical cell culture",
    species: "Human (iPSC)",
    cellLine: "Mixed",
    ageDays: 72,
    metrics: { signal: 0.74, response: 0.77, plasticity: 0.63, learning: 0.64, retention: 0.40, repro: 0.86, composite: 0.67 },
    nOrganoids: 22, nSessions: 96, nBatches: 4, nLabs: 3,
    controls: { randomFeedback: "pass", shamStim: "pass", frozenDecoder: "pass", decoderOnly: "pass", nullStim: "pass", replication: "pass" },
    grade: "A",
    availability: { raw: true, processed: true, code: true, peerReviewed: false, openDataset: true },
    lastUpdated: "2026-04-05",
    learningCurve: mkCurve(0.23, 0.68, 0.03, 0.25),
    datasetId: "ob-ds-0008",
    limitations: ["Independent replication; effect sizes slightly reduced vs original"],
    paper: { title: "Multi-lab replication of DishBrain v2.1 — Pong", authors: ["Independent Consortium"], year: 2026, venue: "Preprint (OSF)", peerReviewed: false },
    culture: "Matched to original",
    preprocessing: "Matched to original",
  },
  {
    id: "ob-sys-0009",
    name: "Muotri — oscillatory dev panel",
    source: "Muotri Lab",
    track: "signal-quality",
    task: "Long-term monitoring",
    platform: "Axion Maestro Pro",
    stimMethod: "None",
    organoidType: "Cortical organoid",
    species: "Human (iPSC)",
    cellLine: "Mixed H1/H9",
    ageDays: 300,
    metrics: { signal: 0.83, response: 0, plasticity: 0, learning: 0, retention: 0, repro: 0.70, composite: 0.77 },
    nOrganoids: 64, nSessions: 210, nBatches: 9, nLabs: 1,
    controls: { randomFeedback: "na", shamStim: "na", frozenDecoder: "na", decoderOnly: "na", nullStim: "pass", replication: "partial" },
    grade: "A",
    availability: { raw: false, processed: true, code: true, peerReviewed: true, openDataset: true },
    lastUpdated: "2026-02-18",
    learningCurve: mkCurve(0.6, 0.83, 0.015, 0.5),
    datasetId: "ob-ds-0009",
    limitations: ["Raw traces available on request only"],
    paper: { title: "10-month oscillatory development in cortical organoids", authors: ["Muotri, A.R. et al."], year: 2023, venue: "Cell Stem Cell", peerReviewed: true },
    culture: "Dorsal forebrain",
    preprocessing: "Axion default",
  },
  {
    id: "ob-sys-0010",
    name: "Organoid intelligence consortium baseline",
    source: "OI Consortium",
    track: "closed-loop-learning",
    task: "Multi-task closed-loop suite",
    platform: "Multiple (pooled)",
    stimMethod: "Electrical + optogenetic",
    decoder: "Task-specific",
    organoidType: "Cerebral organoid (pooled)",
    species: "Human (iPSC)",
    cellLine: "Multiple",
    ageDays: 180,
    metrics: { signal: 0.71, response: 0.72, plasticity: 0.58, learning: 0.55, retention: 0.42, repro: 0.68, composite: 0.61 },
    nOrganoids: 120, nSessions: 360, nBatches: 14, nLabs: 5,
    controls: { randomFeedback: "pass", shamStim: "pass", frozenDecoder: "pass", decoderOnly: "pass", nullStim: "pass", replication: "pass" },
    grade: "A",
    availability: { raw: true, processed: true, code: true, peerReviewed: true, openDataset: true },
    lastUpdated: "2026-04-01",
    learningCurve: mkCurve(0.26, 0.55, 0.025, 0.27),
    datasetId: "ob-ds-0010",
    limitations: ["Pooled across labs; variance is wide", "No cross-task generalization claim"],
    paper: { title: "Organoid intelligence consortium — task suite", authors: ["Smirnova, L. et al."], year: 2025, venue: "Frontiers in Science", peerReviewed: true },
    culture: "Pooled protocols",
    preprocessing: "Unified pipeline, open source",
  },
  {
    id: "ob-sys-0011",
    name: "Brainoware — reservoir speech",
    source: "Indiana Bloomington",
    track: "closed-loop-learning",
    task: "Speech reservoir readout",
    platform: "MaxOne HD-MEA",
    stimMethod: "Electrical pattern encoding",
    decoder: "Linear readout",
    organoidType: "Cerebral organoid",
    species: "Human (iPSC)",
    cellLine: "IMR-90",
    ageDays: 90,
    metrics: { signal: 0.68, response: 0.72, plasticity: 0.54, learning: 0.56, retention: 0.38, repro: 0.42, composite: 0.55 },
    nOrganoids: 12, nSessions: 48, nBatches: 3, nLabs: 1,
    controls: { randomFeedback: "partial", shamStim: "pass", frozenDecoder: "pass", decoderOnly: "pass", nullStim: "pass", replication: "missing" },
    grade: "B",
    availability: { raw: false, processed: true, code: true, peerReviewed: true, openDataset: false },
    lastUpdated: "2025-12-20",
    learningCurve: mkCurve(0.3, 0.58, 0.03, 0.3),
    datasetId: "ob-ds-0011",
    limitations: ["Decoder-only lift is most of the effect", "Small N batches"],
    paper: { title: "Brain organoid reservoir computing for artificial intelligence", authors: ["Cai, H. et al."], year: 2023, venue: "Nature Electronics", peerReviewed: true },
    culture: "Dorsal forebrain, 3 months",
    preprocessing: "Open-source reservoir package",
  },
  {
    id: "ob-sys-0012",
    name: "Cortical organoid — dopaminergic learning",
    source: "FinalSpark",
    track: "plasticity",
    task: "Reward-conditioned induction",
    platform: "Custom MEA",
    stimMethod: "Dopamine + electrical",
    organoidType: "Cortical organoid",
    species: "Human (iPSC)",
    cellLine: "Proprietary",
    ageDays: 140,
    metrics: { signal: 0.69, response: 0.64, plasticity: 0.66, learning: 0.48, retention: 0.52, repro: 0.40, composite: 0.58 },
    nOrganoids: 16, nSessions: 52, nBatches: 3, nLabs: 1,
    controls: { randomFeedback: "na", shamStim: "pass", frozenDecoder: "na", decoderOnly: "na", nullStim: "pass", replication: "missing" },
    grade: "C",
    availability: { raw: false, processed: true, code: false, peerReviewed: false, openDataset: false },
    lastUpdated: "2026-01-20",
    learningCurve: mkCurve(0.3, 0.66, 0.025, 0.3),
    datasetId: "ob-ds-0012",
    limitations: ["Small batches", "Not yet peer reviewed"],
    paper: { title: "Dopamine-gated induction in cortical organoids", authors: ["Jordan, F. et al."], year: 2025, venue: "bioRxiv", peerReviewed: false },
    culture: "Dorsal forebrain 5m",
    preprocessing: "Proprietary",
  },
  {
    id: "ob-sys-0013",
    name: "Pasca midbrain — responsiveness",
    source: "Pasca Lab",
    track: "responsiveness",
    task: "Dopaminergic stimulus response",
    platform: "MaxOne HD-MEA",
    stimMethod: "Pharmacological + electrical",
    organoidType: "Midbrain organoid",
    species: "Human (iPSC)",
    cellLine: "H9",
    ageDays: 220,
    metrics: { signal: 0.78, response: 0.80, plasticity: 0.44, learning: 0, retention: 0, repro: 0.68, composite: 0.63 },
    nOrganoids: 40, nSessions: 120, nBatches: 6, nLabs: 1,
    controls: { randomFeedback: "na", shamStim: "pass", frozenDecoder: "na", decoderOnly: "na", nullStim: "pass", replication: "partial" },
    grade: "B",
    availability: { raw: true, processed: true, code: true, peerReviewed: true, openDataset: true },
    lastUpdated: "2026-03-02",
    learningCurve: mkCurve(0.35, 0.8, 0.02, 0.35),
    datasetId: "ob-ds-0013",
    limitations: ["Single-lab, partial inter-batch replication"],
    paper: { title: "Midbrain organoid stimulus-response assays", authors: ["Pasca, S.P. et al."], year: 2024, venue: "Neuron", peerReviewed: true },
    culture: "Guided midbrain protocol",
    preprocessing: "Public Python pipeline",
  },
  {
    id: "ob-sys-0014",
    name: "Quadros — retinal organoid responsiveness",
    source: "Quadros Lab",
    track: "responsiveness",
    task: "Light-stimulus response",
    platform: "Axion Maestro Edge",
    stimMethod: "Optical (LED panels)",
    organoidType: "Retinal organoid",
    species: "Human (iPSC)",
    cellLine: "CRX-reporter",
    ageDays: 170,
    metrics: { signal: 0.73, response: 0.76, plasticity: 0.30, learning: 0, retention: 0, repro: 0.58, composite: 0.58 },
    nOrganoids: 36, nSessions: 84, nBatches: 4, nLabs: 1,
    controls: { randomFeedback: "na", shamStim: "pass", frozenDecoder: "na", decoderOnly: "na", nullStim: "pass", replication: "partial" },
    grade: "B",
    availability: { raw: true, processed: true, code: true, peerReviewed: true, openDataset: true },
    lastUpdated: "2026-01-28",
    learningCurve: mkCurve(0.3, 0.76, 0.025, 0.32),
    datasetId: "ob-ds-0014",
    limitations: ["Optical stim has batch-level variance"],
    paper: { title: "Light-driven activity in retinal organoids", authors: ["Quadros, R.M. et al."], year: 2024, venue: "eLife", peerReviewed: true },
    culture: "3D retinal protocol",
    preprocessing: "Axion + open-source",
  },
  {
    id: "ob-sys-0015",
    name: "Muotri — Rett syndrome signal",
    source: "Muotri Lab",
    track: "signal-quality",
    task: "Disease-model spontaneous activity",
    platform: "Axion Maestro Pro",
    stimMethod: "None",
    organoidType: "Cortical organoid",
    species: "Human (iPSC, MECP2-/-)",
    cellLine: "MECP2-KO",
    ageDays: 200,
    metrics: { signal: 0.72, response: 0, plasticity: 0, learning: 0, retention: 0, repro: 0.66, composite: 0.69 },
    nOrganoids: 48, nSessions: 144, nBatches: 6, nLabs: 1,
    controls: { randomFeedback: "na", shamStim: "na", frozenDecoder: "na", decoderOnly: "na", nullStim: "pass", replication: "partial" },
    grade: "B",
    availability: { raw: false, processed: true, code: true, peerReviewed: true, openDataset: false },
    lastUpdated: "2025-12-10",
    learningCurve: mkCurve(0.45, 0.72, 0.02, 0.35),
    datasetId: "ob-ds-0015",
    limitations: ["Raw traces on request", "Disease comparison needs more batches"],
    paper: { title: "MECP2 organoids show altered burst structure", authors: ["Trujillo, C.A. et al."], year: 2021, venue: "Cell Stem Cell", peerReviewed: true },
    culture: "Dorsal forebrain, MECP2 patient line",
    preprocessing: "Axion + Python burst detection",
  },
  {
    id: "ob-sys-0016",
    name: "Koch — assembloid closed-loop",
    source: "Koch Lab",
    track: "closed-loop-learning",
    task: "Reach-to-target (virtual)",
    platform: "3Brain BioCAM X",
    stimMethod: "Patterned electrical",
    decoder: "Kalman filter",
    organoidType: "Cortico-thalamic assembloid",
    species: "Human (iPSC)",
    cellLine: "H1",
    ageDays: 150,
    metrics: { signal: 0.70, response: 0.74, plasticity: 0.57, learning: 0.60, retention: 0.46, repro: 0.58, composite: 0.61 },
    nOrganoids: 20, nSessions: 72, nBatches: 4, nLabs: 2,
    controls: { randomFeedback: "pass", shamStim: "pass", frozenDecoder: "pass", decoderOnly: "pass", nullStim: "pass", replication: "partial" },
    grade: "B",
    availability: { raw: true, processed: true, code: true, peerReviewed: true, openDataset: true },
    lastUpdated: "2026-03-18",
    learningCurve: mkCurve(0.28, 0.60, 0.03, 0.28),
    datasetId: "ob-ds-0016",
    limitations: ["Decoder is well-tuned; independent lift is modest"],
    paper: { title: "Cortico-thalamic assembloids in closed-loop reach tasks", authors: ["Koch, C. et al."], year: 2025, venue: "Cell", peerReviewed: true },
    culture: "Fused assembloid",
    preprocessing: "Open-source",
  },
  {
    id: "ob-sys-0017",
    name: "Hartung — retention panel",
    source: "Hartung Lab",
    track: "retention",
    task: "Re-exposure at 24h, 7d",
    platform: "MaxOne HD-MEA",
    stimMethod: "Electrical",
    decoder: "Logistic",
    organoidType: "Cortical organoid",
    species: "Human (iPSC)",
    cellLine: "H9",
    ageDays: 140,
    metrics: { signal: 0.72, response: 0.68, plasticity: 0.58, learning: 0.50, retention: 0.63, repro: 0.54, composite: 0.60 },
    nOrganoids: 24, nSessions: 72, nBatches: 4, nLabs: 1,
    controls: { randomFeedback: "pass", shamStim: "pass", frozenDecoder: "pass", decoderOnly: "partial", nullStim: "pass", replication: "partial" },
    grade: "B",
    availability: { raw: true, processed: true, code: true, peerReviewed: true, openDataset: true },
    lastUpdated: "2026-02-28",
    learningCurve: mkCurve(0.32, 0.63, 0.02, 0.32),
    datasetId: "ob-ds-0017",
    limitations: ["Retention effect size moderate", "Naive baseline uses separate batch"],
    paper: { title: "Organoid memory across 7 days", authors: ["Hartung, T. et al."], year: 2025, venue: "Journal of Neural Engineering", peerReviewed: true },
    culture: "Dorsal forebrain",
    preprocessing: "Open-source",
  },
  {
    id: "ob-sys-0018",
    name: "Cortical organoid — cross-lab plasticity",
    source: "Multi-site",
    track: "plasticity",
    task: "Paired-pathway induction",
    platform: "Axion Maestro Pro (pooled)",
    stimMethod: "Theta-burst electrical",
    organoidType: "Cortical organoid",
    species: "Human (iPSC, pooled)",
    cellLine: "Multiple",
    ageDays: 200,
    metrics: { signal: 0.74, response: 0.70, plasticity: 0.67, learning: 0, retention: 0.55, repro: 0.78, composite: 0.66 },
    nOrganoids: 58, nSessions: 174, nBatches: 10, nLabs: 4,
    controls: { randomFeedback: "na", shamStim: "pass", frozenDecoder: "na", decoderOnly: "na", nullStim: "pass", replication: "pass" },
    grade: "A",
    availability: { raw: true, processed: true, code: true, peerReviewed: true, openDataset: true },
    lastUpdated: "2026-04-10",
    learningCurve: mkCurve(0.3, 0.67, 0.02, 0.3),
    datasetId: "ob-ds-0018",
    limitations: ["Meta-analysis; heterogeneous induction protocols"],
    paper: { title: "Cross-lab plasticity in cortical organoids", authors: ["Consortium"], year: 2025, venue: "Nature Methods", peerReviewed: true },
    culture: "Pooled cortical protocols",
    preprocessing: "Unified pipeline",
  },
  {
    id: "ob-sys-0019",
    name: "Chen — Pong replication",
    source: "Chen Lab (Indiana)",
    track: "closed-loop-learning",
    task: "Pong-style goal reaching",
    platform: "MaxOne HD-MEA",
    stimMethod: "Matched electrical",
    decoder: "Rate-coded binary",
    organoidType: "Cortical cell culture",
    species: "Human (iPSC)",
    cellLine: "H1",
    ageDays: 70,
    metrics: { signal: 0.71, response: 0.74, plasticity: 0.60, learning: 0.60, retention: 0.38, repro: 0.72, composite: 0.62 },
    nOrganoids: 16, nSessions: 64, nBatches: 3, nLabs: 1,
    controls: { randomFeedback: "pass", shamStim: "pass", frozenDecoder: "pass", decoderOnly: "pass", nullStim: "pass", replication: "partial" },
    grade: "B",
    availability: { raw: true, processed: true, code: true, peerReviewed: false, openDataset: true },
    lastUpdated: "2026-02-14",
    learningCurve: mkCurve(0.24, 0.60, 0.03, 0.25),
    datasetId: "ob-ds-0008",
    limitations: ["One of multiple replications; effect size slightly smaller"],
    paper: { title: "Independent replication of Kagan et al. (2022)", authors: ["Chen, X. et al."], year: 2026, venue: "bioRxiv", peerReviewed: false },
    culture: "Matched to original",
    preprocessing: "Open-source",
  },
  {
    id: "ob-sys-0020",
    name: "Cortical organoid — long retention",
    source: "Hartung Lab",
    track: "retention",
    task: "30-day retention",
    platform: "MaxOne HD-MEA",
    stimMethod: "Electrical",
    decoder: "Logistic",
    organoidType: "Cortical organoid",
    species: "Human (iPSC)",
    cellLine: "H9",
    ageDays: 160,
    metrics: { signal: 0.70, response: 0.66, plasticity: 0.55, learning: 0.46, retention: 0.52, repro: 0.48, composite: 0.56 },
    nOrganoids: 14, nSessions: 42, nBatches: 3, nLabs: 1,
    controls: { randomFeedback: "pass", shamStim: "pass", frozenDecoder: "pass", decoderOnly: "partial", nullStim: "pass", replication: "missing" },
    grade: "C",
    availability: { raw: true, processed: true, code: true, peerReviewed: false, openDataset: true },
    lastUpdated: "2026-03-08",
    learningCurve: mkCurve(0.35, 0.52, 0.02, 0.3),
    datasetId: "ob-ds-0017",
    limitations: ["Small N at 30-day timepoint"],
    paper: { title: "30-day retention in cortical organoids (preprint)", authors: ["Hartung, T. et al."], year: 2026, venue: "bioRxiv", peerReviewed: false },
    culture: "Dorsal forebrain",
    preprocessing: "Open-source",
  },
  {
    id: "ob-sys-0021",
    name: "Muotri — signal reference panel v2",
    source: "Muotri Lab",
    track: "reproducibility",
    task: "Reference panel (signal)",
    platform: "Axion Maestro Pro",
    stimMethod: "None",
    organoidType: "Cortical organoid",
    species: "Human (iPSC)",
    cellLine: "Mixed",
    ageDays: 250,
    metrics: { signal: 0.80, response: 0, plasticity: 0, learning: 0, retention: 0, repro: 0.84, composite: 0.78 },
    nOrganoids: 96, nSessions: 288, nBatches: 12, nLabs: 4,
    controls: { randomFeedback: "na", shamStim: "na", frozenDecoder: "na", decoderOnly: "na", nullStim: "pass", replication: "pass" },
    grade: "A",
    availability: { raw: true, processed: true, code: true, peerReviewed: true, openDataset: true },
    lastUpdated: "2026-04-12",
    learningCurve: mkCurve(0.55, 0.84, 0.015, 0.5),
    datasetId: "ob-ds-0009",
    limitations: ["Signal-only reference panel; no task"],
    paper: { title: "Cross-lab reference panel for cortical organoid activity", authors: ["Muotri, A.R. et al."], year: 2026, venue: "Nature Methods", peerReviewed: true },
    culture: "Pooled cortical",
    preprocessing: "Unified",
  },
  {
    id: "ob-sys-0022",
    name: "Midbrain organoid reward response",
    source: "Pasca Lab",
    track: "responsiveness",
    task: "Reward-coupled stimulation",
    platform: "MaxOne HD-MEA",
    stimMethod: "Dopaminergic + electrical",
    organoidType: "Midbrain organoid",
    species: "Human (iPSC)",
    cellLine: "H9",
    ageDays: 200,
    metrics: { signal: 0.72, response: 0.74, plasticity: 0.42, learning: 0, retention: 0, repro: 0.54, composite: 0.60 },
    nOrganoids: 24, nSessions: 72, nBatches: 4, nLabs: 1,
    controls: { randomFeedback: "na", shamStim: "pass", frozenDecoder: "na", decoderOnly: "na", nullStim: "pass", replication: "missing" },
    grade: "B",
    availability: { raw: true, processed: true, code: true, peerReviewed: false, openDataset: true },
    lastUpdated: "2026-01-09",
    learningCurve: mkCurve(0.35, 0.74, 0.025, 0.35),
    datasetId: "ob-ds-0013",
    limitations: ["Preprint; single lab"],
    paper: { title: "Reward coupling in midbrain organoids", authors: ["Pasca, S.P. et al."], year: 2025, venue: "bioRxiv", peerReviewed: false },
    culture: "Midbrain protocol",
    preprocessing: "Open-source",
  },
  {
    id: "ob-sys-0023",
    name: "FinalSpark 2024 baseline",
    source: "FinalSpark",
    track: "signal-quality",
    task: "Platform baseline",
    platform: "Custom MEA",
    stimMethod: "None",
    organoidType: "Cortical spheroid",
    species: "Human (iPSC)",
    cellLine: "Proprietary",
    ageDays: 100,
    metrics: { signal: 0.70, response: 0, plasticity: 0, learning: 0, retention: 0, repro: 0.50, composite: 0.64 },
    nOrganoids: 64, nSessions: 192, nBatches: 8, nLabs: 1,
    controls: { randomFeedback: "na", shamStim: "na", frozenDecoder: "na", decoderOnly: "na", nullStim: "pass", replication: "missing" },
    grade: "B",
    availability: { raw: false, processed: true, code: false, peerReviewed: false, openDataset: false },
    lastUpdated: "2025-11-30",
    learningCurve: mkCurve(0.5, 0.7, 0.02, 0.4),
    datasetId: "ob-ds-0003",
    limitations: ["Commercial baseline; limited public data"],
    paper: { title: "FinalSpark 2024 platform baseline", authors: ["FinalSpark Team"], year: 2024, venue: "Tech report", peerReviewed: false },
    culture: "Proprietary bioreactor",
    preprocessing: "Proprietary",
  },
  {
    id: "ob-sys-0024",
    name: "Lancaster — ion-channel perturbation",
    source: "Lancaster Lab",
    track: "responsiveness",
    task: "TTX / GBZ perturbation",
    platform: "3Brain BioCAM X",
    stimMethod: "Electrical + pharmacology",
    organoidType: "Whole-brain organoid",
    species: "Human (iPSC)",
    cellLine: "HMGU1",
    ageDays: 220,
    metrics: { signal: 0.78, response: 0.72, plasticity: 0.38, learning: 0, retention: 0, repro: 0.62, composite: 0.60 },
    nOrganoids: 30, nSessions: 90, nBatches: 4, nLabs: 1,
    controls: { randomFeedback: "na", shamStim: "pass", frozenDecoder: "na", decoderOnly: "na", nullStim: "pass", replication: "partial" },
    grade: "B",
    availability: { raw: true, processed: true, code: true, peerReviewed: true, openDataset: true },
    lastUpdated: "2026-01-25",
    learningCurve: mkCurve(0.4, 0.72, 0.02, 0.35),
    datasetId: "ob-ds-0004",
    limitations: ["Pharmacology batches small"],
    paper: { title: "Ion-channel perturbation in cerebral organoids", authors: ["Lancaster, M.A. et al."], year: 2024, venue: "eLife", peerReviewed: true },
    culture: "Unguided cerebral",
    preprocessing: "Open-source",
  },
  {
    id: "ob-sys-0025",
    name: "Kagan — extended retention (24h)",
    source: "Kagan Lab",
    track: "retention",
    task: "Pong re-exposure 24h",
    platform: "MaxOne HD-MEA",
    stimMethod: "Matched",
    decoder: "Matched",
    organoidType: "Cortical cell culture",
    species: "Human (iPSC)",
    cellLine: "Mixed",
    ageDays: 72,
    metrics: { signal: 0.76, response: 0.78, plasticity: 0.62, learning: 0.66, retention: 0.56, repro: 0.60, composite: 0.66 },
    nOrganoids: 24, nSessions: 96, nBatches: 4, nLabs: 2,
    controls: { randomFeedback: "pass", shamStim: "pass", frozenDecoder: "pass", decoderOnly: "pass", nullStim: "pass", replication: "partial" },
    grade: "A",
    availability: { raw: true, processed: true, code: true, peerReviewed: true, openDataset: true },
    lastUpdated: "2026-03-22",
    learningCurve: mkCurve(0.26, 0.66, 0.025, 0.26),
    datasetId: "ob-ds-0001",
    limitations: ["24h window only"],
    paper: { title: "24h retention of Pong performance in DishBrain v2", authors: ["Kagan, B.J. et al."], year: 2024, venue: "Neuron", peerReviewed: true },
    culture: "2D MEA cortical",
    preprocessing: "Kilosort3",
  },
  {
    id: "ob-sys-0026",
    name: "Assembloid reservoir — MNIST",
    source: "Koch Lab",
    track: "closed-loop-learning",
    task: "MNIST reservoir classification",
    platform: "3Brain BioCAM X",
    stimMethod: "Patterned electrical",
    decoder: "Linear readout",
    organoidType: "Cortico-thalamic assembloid",
    species: "Human (iPSC)",
    cellLine: "H1",
    ageDays: 150,
    metrics: { signal: 0.68, response: 0.70, plasticity: 0.50, learning: 0.52, retention: 0.32, repro: 0.44, composite: 0.54 },
    nOrganoids: 14, nSessions: 48, nBatches: 3, nLabs: 1,
    controls: { randomFeedback: "partial", shamStim: "pass", frozenDecoder: "pass", decoderOnly: "pass", nullStim: "pass", replication: "missing" },
    grade: "C",
    availability: { raw: false, processed: true, code: true, peerReviewed: false, openDataset: false },
    lastUpdated: "2026-02-06",
    learningCurve: mkCurve(0.3, 0.52, 0.03, 0.3),
    datasetId: "ob-ds-0016",
    limitations: ["Mostly decoder-driven", "Small N"],
    paper: { title: "Reservoir MNIST with cortico-thalamic assembloids", authors: ["Koch, C. et al."], year: 2025, venue: "bioRxiv", peerReviewed: false },
    culture: "Fused assembloid",
    preprocessing: "Open-source",
  },
  {
    id: "ob-sys-0027",
    name: "Retinal organoid long-term retention",
    source: "Quadros Lab",
    track: "retention",
    task: "Re-exposure to light protocol",
    platform: "Axion Maestro Edge",
    stimMethod: "Optical",
    organoidType: "Retinal organoid",
    species: "Human (iPSC)",
    cellLine: "CRX-reporter",
    ageDays: 200,
    metrics: { signal: 0.70, response: 0.72, plasticity: 0.36, learning: 0, retention: 0.48, repro: 0.50, composite: 0.52 },
    nOrganoids: 18, nSessions: 54, nBatches: 3, nLabs: 1,
    controls: { randomFeedback: "na", shamStim: "pass", frozenDecoder: "na", decoderOnly: "na", nullStim: "pass", replication: "missing" },
    grade: "C",
    availability: { raw: true, processed: true, code: true, peerReviewed: false, openDataset: true },
    lastUpdated: "2026-03-04",
    learningCurve: mkCurve(0.3, 0.48, 0.02, 0.3),
    datasetId: "ob-ds-0014",
    limitations: ["Retention defined on light-response amplitude, not behavior"],
    paper: { title: "Retinal organoid retention across protocols", authors: ["Quadros, R.M. et al."], year: 2026, venue: "bioRxiv", peerReviewed: false },
    culture: "3D retinal",
    preprocessing: "Open-source",
  },
  {
    id: "ob-sys-0028",
    name: "Organoid vs in vivo comparison",
    source: "Multi-site",
    track: "reproducibility",
    task: "Cross-system stimulus comparison",
    platform: "Multiple",
    stimMethod: "Matched electrical",
    organoidType: "Cortical organoid vs slice",
    species: "Human (iPSC) vs mouse",
    cellLine: "Multiple",
    ageDays: 180,
    metrics: { signal: 0.66, response: 0.68, plasticity: 0.42, learning: 0, retention: 0, repro: 0.80, composite: 0.63 },
    nOrganoids: 72, nSessions: 200, nBatches: 11, nLabs: 4,
    controls: { randomFeedback: "na", shamStim: "pass", frozenDecoder: "na", decoderOnly: "na", nullStim: "pass", replication: "pass" },
    grade: "A",
    availability: { raw: true, processed: true, code: true, peerReviewed: true, openDataset: true },
    lastUpdated: "2026-04-15",
    learningCurve: mkCurve(0.3, 0.8, 0.02, 0.3),
    datasetId: "ob-ds-0009",
    limitations: ["Comparison depends on matched electrode layout assumptions"],
    paper: { title: "Organoid vs in vivo electrophysiology — a cross-system study", authors: ["Consortium"], year: 2026, venue: "Neuron", peerReviewed: true },
    culture: "Various",
    preprocessing: "Unified",
  },
  {
    id: "ob-sys-0029",
    name: "Knoblich — oscillatory plasticity",
    source: "Knoblich Lab",
    track: "plasticity",
    task: "Theta-induction plasticity",
    platform: "MaxOne HD-MEA",
    stimMethod: "Theta-burst electrical",
    organoidType: "Cerebral organoid",
    species: "Human (iPSC)",
    cellLine: "KOLF2.1J",
    ageDays: 200,
    metrics: { signal: 0.78, response: 0.66, plasticity: 0.70, learning: 0, retention: 0.50, repro: 0.66, composite: 0.66 },
    nOrganoids: 32, nSessions: 96, nBatches: 4, nLabs: 2,
    controls: { randomFeedback: "na", shamStim: "pass", frozenDecoder: "na", decoderOnly: "na", nullStim: "pass", replication: "partial" },
    grade: "A",
    availability: { raw: true, processed: true, code: true, peerReviewed: true, openDataset: true },
    lastUpdated: "2026-04-02",
    learningCurve: mkCurve(0.3, 0.7, 0.02, 0.32),
    datasetId: "ob-ds-0006",
    limitations: ["Cross-batch effect size moderate"],
    paper: { title: "Theta-induced plasticity in cerebral organoids", authors: ["Knoblich, J.A. et al."], year: 2025, venue: "Nature Communications", peerReviewed: true },
    culture: "Guided cerebral",
    preprocessing: "Open-source",
  },
  {
    id: "ob-sys-0030",
    name: "Finkbeiner — extended closed-loop",
    source: "Finkbeiner Lab",
    track: "closed-loop-learning",
    task: "Multi-session cart-pole",
    platform: "MaxOne HD-MEA",
    stimMethod: "Patterned electrical",
    decoder: "LSTM on rate vectors",
    organoidType: "Cortical organoid",
    species: "Human (iPSC)",
    cellLine: "WTC-11",
    ageDays: 170,
    metrics: { signal: 0.72, response: 0.74, plasticity: 0.58, learning: 0.65, retention: 0.52, repro: 0.58, composite: 0.64 },
    nOrganoids: 22, nSessions: 110, nBatches: 5, nLabs: 2,
    controls: { randomFeedback: "pass", shamStim: "pass", frozenDecoder: "pass", decoderOnly: "pass", nullStim: "pass", replication: "partial" },
    grade: "B",
    availability: { raw: true, processed: true, code: true, peerReviewed: true, openDataset: true },
    lastUpdated: "2026-04-08",
    learningCurve: mkCurve(0.24, 0.65, 0.03, 0.25),
    datasetId: "ob-ds-0007",
    limitations: ["Multi-session improvement requires careful matching"],
    paper: { title: "Extended closed-loop cart-pole with cortical organoids", authors: ["Finkbeiner, S. et al."], year: 2026, venue: "Cell Reports", peerReviewed: true },
    culture: "Dorsal forebrain",
    preprocessing: "Kilosort3 + Phy",
  },
];

export const systemById = (id: string) => SYSTEMS.find((s) => s.id === id);

export type Dataset = {
  id: string;
  name: string;
  source: string;
  modality: string;
  platform: string;
  species: string;
  organoidType: string;
  nOrganoids: number;
  nSessions: number;
  duration: string;
  size: string;
  license: string;
  access: "Open" | "Restricted" | "On request";
  raw: boolean;
  processed: boolean;
  code: boolean;
  description: string;
  tracks: Track[];
  lastUpdated: string;
  files?: { name: string; format: string; note?: string }[];
};

export const DATASETS: Dataset[] = [
  {
    id: "ob-ds-0001", name: "DishBrain v2.1 — Pong sessions",
    source: "Kagan Lab", modality: "HD-MEA + task logs", platform: "MaxOne", species: "Human iPSC + mouse",
    organoidType: "Cortical cell culture",
    nOrganoids: 38, nSessions: 176, duration: "264 h", size: "2.1 TB raw", license: "CC-BY-4.0", access: "Open",
    raw: true, processed: true, code: true,
    description: "Full session logs and spike events for 176 pong-style closed-loop sessions.",
    tracks: ["closed-loop-learning", "signal-quality"],
    lastUpdated: "2026-04-18",
    files: [
      { name: "traces.nwb", format: ".nwb" },
      { name: "spikes.parquet", format: ".parquet" },
      { name: "task_trajectories.parquet", format: ".parquet" },
      { name: "session_meta.json", format: ".json" },
    ],
  },
  {
    id: "ob-ds-0002", name: "Muotri oscillation corpus",
    source: "Muotri Lab", modality: "HD-MEA", platform: "Axion Maestro Pro", species: "Human iPSC",
    organoidType: "Cortical organoid",
    nOrganoids: 54, nSessions: 108, duration: "1080 h", size: "450 GB processed", license: "CC-BY-NC-4.0", access: "Restricted",
    raw: false, processed: true, code: true,
    description: "Long-term oscillatory recordings from cortical organoids (processed only).",
    tracks: ["signal-quality", "responsiveness"],
    lastUpdated: "2026-02-22",
  },
  {
    id: "ob-ds-0003", name: "FinalSpark CL-01 exports",
    source: "FinalSpark", modality: "Custom MEA + stim log", platform: "Custom", species: "Human iPSC",
    organoidType: "Cortical spheroid",
    nOrganoids: 28, nSessions: 94, duration: "188 h", size: "72 GB", license: "Proprietary", access: "On request",
    raw: false, processed: true, code: false,
    description: "Processed exports from the CL-01 closed-loop platform.",
    tracks: ["closed-loop-learning", "plasticity"],
    lastUpdated: "2026-03-30",
  },
  {
    id: "ob-ds-0004", name: "Lancaster plasticity panel",
    source: "Lancaster Lab", modality: "HD-MEA + induction logs", platform: "3Brain BioCAM DupleX", species: "Human iPSC",
    organoidType: "Whole-brain organoid",
    nOrganoids: 22, nSessions: 62, duration: "186 h", size: "180 GB", license: "CC-BY-4.0", access: "Open",
    raw: true, processed: true, code: true,
    description: "Pre/post induction recordings for paired-pathway plasticity experiments.",
    tracks: ["plasticity", "responsiveness"],
    lastUpdated: "2026-01-12",
    files: [
      { name: "pre_post.nwb", format: ".nwb" },
      { name: "spikes.parquet", format: ".parquet" },
      { name: "induction_log.json", format: ".json" },
    ],
  },
  {
    id: "ob-ds-0005", name: "BrainXell assembloid retention",
    source: "BrainXell", modality: "HD-MEA + task logs", platform: "Axion Maestro CytoView", species: "Human iPSC",
    organoidType: "Cortico-striatal assembloid",
    nOrganoids: 18, nSessions: 54, duration: "108 h", size: "48 GB", license: "Proprietary", access: "On request",
    raw: false, processed: true, code: false,
    description: "Matched re-exposure sessions at 24h and 7d post-training.",
    tracks: ["retention", "closed-loop-learning"],
    lastUpdated: "2025-12-02",
  },
  {
    id: "ob-ds-0006", name: "Knoblich reference spontaneous panel",
    source: "Knoblich Lab", modality: "HD-MEA", platform: "MaxOne", species: "Human iPSC",
    organoidType: "Cerebral organoid",
    nOrganoids: 42, nSessions: 126, duration: "252 h", size: "1.1 TB raw", license: "CC-BY-4.0", access: "Open",
    raw: true, processed: true, code: true,
    description: "Reference spontaneous-activity dataset across 42 organoids, 5 batches.",
    tracks: ["signal-quality", "plasticity"],
    lastUpdated: "2026-04-02",
    files: [
      { name: "traces.nwb", format: ".nwb" },
      { name: "bursts.parquet", format: ".parquet" },
    ],
  },
  {
    id: "ob-ds-0007", name: "Finkbeiner cart-pole sessions",
    source: "Finkbeiner Lab", modality: "HD-MEA + task logs", platform: "MaxOne", species: "Human iPSC",
    organoidType: "Cortical organoid",
    nOrganoids: 26, nSessions: 110, duration: "220 h", size: "850 GB", license: "CC-BY-4.0", access: "Open",
    raw: true, processed: true, code: true,
    description: "Closed-loop cart-pole sessions with LSTM decoder logs.",
    tracks: ["closed-loop-learning", "retention"],
    lastUpdated: "2026-04-08",
  },
  {
    id: "ob-ds-0008", name: "Pong multi-lab replication",
    source: "Independent Consortium", modality: "HD-MEA + task logs", platform: "MaxOne", species: "Human iPSC + mouse",
    organoidType: "Cortical cell culture",
    nOrganoids: 38, nSessions: 160, duration: "240 h", size: "1.8 TB", license: "CC-BY-4.0", access: "Open",
    raw: true, processed: true, code: true,
    description: "Cross-lab replication of DishBrain v2.1 — Pong sessions.",
    tracks: ["reproducibility", "closed-loop-learning"],
    lastUpdated: "2026-04-05",
  },
  {
    id: "ob-ds-0009", name: "Cross-lab reference panel v2",
    source: "Multi-site", modality: "HD-MEA", platform: "Multiple", species: "Human iPSC",
    organoidType: "Cortical organoid (pooled)",
    nOrganoids: 96, nSessions: 288, duration: "576 h", size: "2.9 TB", license: "CC-BY-4.0", access: "Open",
    raw: true, processed: true, code: true,
    description: "Cross-lab reference panel for baseline organoid activity.",
    tracks: ["reproducibility", "signal-quality"],
    lastUpdated: "2026-04-12",
  },
  {
    id: "ob-ds-0010", name: "OI consortium task suite",
    source: "OI Consortium", modality: "HD-MEA + task logs", platform: "Multiple", species: "Human iPSC",
    organoidType: "Cerebral organoid (pooled)",
    nOrganoids: 120, nSessions: 360, duration: "720 h", size: "4.5 TB", license: "CC-BY-4.0", access: "Open",
    raw: true, processed: true, code: true,
    description: "Pooled task suite across five labs and four task families.",
    tracks: ["closed-loop-learning", "reproducibility"],
    lastUpdated: "2026-04-01",
  },
  {
    id: "ob-ds-0011", name: "Brainoware reservoir sessions",
    source: "Indiana Bloomington", modality: "HD-MEA + audio embeddings", platform: "MaxOne", species: "Human iPSC",
    organoidType: "Cerebral organoid",
    nOrganoids: 12, nSessions: 48, duration: "72 h", size: "120 GB processed", license: "CC-BY-NC-4.0", access: "Restricted",
    raw: false, processed: true, code: true,
    description: "Reservoir-computing sessions for speech classification.",
    tracks: ["closed-loop-learning"],
    lastUpdated: "2025-12-20",
  },
  {
    id: "ob-ds-0012", name: "Dopamine-gated plasticity corpus",
    source: "FinalSpark", modality: "Custom MEA + dopamine log", platform: "Custom", species: "Human iPSC",
    organoidType: "Cortical organoid",
    nOrganoids: 16, nSessions: 52, duration: "104 h", size: "38 GB", license: "Proprietary", access: "On request",
    raw: false, processed: true, code: false,
    description: "Reward-conditioned plasticity experiments.",
    tracks: ["plasticity"],
    lastUpdated: "2026-01-20",
  },
  {
    id: "ob-ds-0013", name: "Pasca midbrain responsiveness",
    source: "Pasca Lab", modality: "HD-MEA + pharmacology", platform: "MaxOne", species: "Human iPSC",
    organoidType: "Midbrain organoid",
    nOrganoids: 40, nSessions: 120, duration: "240 h", size: "720 GB", license: "CC-BY-4.0", access: "Open",
    raw: true, processed: true, code: true,
    description: "Stimulus-response assays in midbrain organoids.",
    tracks: ["responsiveness", "signal-quality"],
    lastUpdated: "2026-03-02",
  },
  {
    id: "ob-ds-0014", name: "Retinal organoid light-stim corpus",
    source: "Quadros Lab", modality: "MEA + optical stim", platform: "Axion Maestro Edge", species: "Human iPSC",
    organoidType: "Retinal organoid",
    nOrganoids: 36, nSessions: 84, duration: "168 h", size: "260 GB", license: "CC-BY-4.0", access: "Open",
    raw: true, processed: true, code: true,
    description: "Light-driven activity across protocols and intensities.",
    tracks: ["responsiveness", "retention"],
    lastUpdated: "2026-01-28",
  },
  {
    id: "ob-ds-0015", name: "Rett syndrome organoid panel",
    source: "Muotri Lab", modality: "HD-MEA", platform: "Axion Maestro Pro", species: "Human iPSC (MECP2-/-)",
    organoidType: "Cortical organoid",
    nOrganoids: 48, nSessions: 144, duration: "288 h", size: "380 GB", license: "CC-BY-NC-4.0", access: "Restricted",
    raw: false, processed: true, code: true,
    description: "MECP2-KO vs WT organoid spontaneous activity.",
    tracks: ["signal-quality"],
    lastUpdated: "2025-12-10",
  },
  {
    id: "ob-ds-0016", name: "Koch assembloid closed-loop",
    source: "Koch Lab", modality: "HD-MEA + task logs", platform: "3Brain BioCAM X", species: "Human iPSC",
    organoidType: "Cortico-thalamic assembloid",
    nOrganoids: 20, nSessions: 72, duration: "144 h", size: "280 GB", license: "CC-BY-4.0", access: "Open",
    raw: true, processed: true, code: true,
    description: "Closed-loop reach task sessions.",
    tracks: ["closed-loop-learning"],
    lastUpdated: "2026-03-18",
  },
  {
    id: "ob-ds-0017", name: "Hartung retention corpus",
    source: "Hartung Lab", modality: "HD-MEA + re-exposure logs", platform: "MaxOne", species: "Human iPSC",
    organoidType: "Cortical organoid",
    nOrganoids: 24, nSessions: 72, duration: "144 h", size: "220 GB", license: "CC-BY-4.0", access: "Open",
    raw: true, processed: true, code: true,
    description: "Retention at 24h and 7d after closed-loop training.",
    tracks: ["retention"],
    lastUpdated: "2026-02-28",
  },
  {
    id: "ob-ds-0018", name: "Cross-lab plasticity meta-dataset",
    source: "Multi-site", modality: "HD-MEA", platform: "Multiple", species: "Human iPSC",
    organoidType: "Cortical organoid (pooled)",
    nOrganoids: 58, nSessions: 174, duration: "348 h", size: "1.3 TB", license: "CC-BY-4.0", access: "Open",
    raw: true, processed: true, code: true,
    description: "Harmonized plasticity experiments across four labs.",
    tracks: ["plasticity", "reproducibility"],
    lastUpdated: "2026-04-10",
  },
];

export const datasetById = (id: string) => DATASETS.find((d) => d.id === id);

export const STATUS_COUNTS = {
  systems: SYSTEMS.length,
  organoids: SYSTEMS.reduce((a, s) => a + s.nOrganoids, 0),
  datasets: DATASETS.length,
  labs: Array.from(new Set(SYSTEMS.map((s) => s.source))).length,
  lastUpdated: "2026-04-20",
  methodologyVersion: "v1.3.0",
};

export const RECENT_UPDATES: { date: string; type: string; text: string; href?: string }[] = [
  { date: "2026-04-18", type: "System", text: "ob-sys-0001 retention sub-score updated after consortium re-analysis", href: "/systems/ob-sys-0001" },
  { date: "2026-04-15", type: "System", text: "ob-sys-0028 added — organoid vs in vivo cross-system comparison", href: "/systems/ob-sys-0028" },
  { date: "2026-04-12", type: "Dataset", text: "ob-ds-0009 cross-lab reference panel v2 released", href: "/datasets/ob-ds-0009" },
  { date: "2026-04-10", type: "System", text: "ob-sys-0018 added — cross-lab plasticity meta-analysis", href: "/systems/ob-sys-0018" },
  { date: "2026-04-08", type: "System", text: "ob-sys-0030 added — Finkbeiner extended closed-loop", href: "/systems/ob-sys-0030" },
  { date: "2026-04-05", type: "System", text: "ob-sys-0008 independent replication moved to grade A", href: "/systems/ob-sys-0008" },
  { date: "2026-04-02", type: "Methodology", text: "v1.3.0 — decoder-only control required for closed-loop track", href: "/about#methodology" },
  { date: "2026-03-30", type: "System", text: "ob-sys-0003 FinalSpark CL-01 scoring updated", href: "/systems/ob-sys-0003" },
];

export const systemsForTrack = (t: Track) => SYSTEMS.filter((s) => s.track === t);

export const searchIndex = [
  ...SYSTEMS.map((s) => ({ type: "system", id: s.id, title: s.name, subtitle: `${s.source} · ${s.track}`, href: `/systems/${s.id}` })),
  ...DATASETS.map((d) => ({ type: "dataset", id: d.id, title: d.name, subtitle: `${d.source} · ${d.modality}`, href: `/datasets/${d.id}` })),
  ...TRACKS.map((t) => ({ type: "track", id: t.id, title: t.name, subtitle: t.short, href: `/benchmarks/${t.id}` })),
];
